global:
  namespace: netbird

management:
  configmap: |-
    {
      "Stuns": [
        {
          "Proto": "udp",
          "URI": "stun:netbird.example.com:31821",
          "Username": "",
          "Password": ""
        }
      ],
      "TURNConfig": {
        "TimeBasedCredentials": false,
        "CredentialsTTL": "12h0m0s",
        "Secret": "secret",
        "Turns": [
          {
            "Proto": "udp",
            "URI": "turn:netbird.example.com:31821",
            "Username": "{{ .STUNNER_AUTH_USER }}",
            "Password": "{{ .STUNNER_AUTH_PASS }}"
          }
        ]
      },
      "Signal": {
        "Proto": "https",
        "URI": "netbird.example.com:443",
        "Username": "",
        "Password": ""
      },
      "Datadir": "/var/lib/netbird/",
      "DataStoreEncryptionKey": "{{ .DATASTORE_ENCRYPTION_KEY }}",
      "HttpConfig": {
        "AuthIssuer": "https://zitadel.example.com",
        "AuthAudience": "{{ .NETBIRD_CLIENT_ID }}",
        "OIDCConfigEndpoint": "https://zitadel.example.com/.well-known/openid-configuration",
        "AuthKeysLocation": "https://zitadel.example.com/oauth/v2/keys",
        "LetsEncryptDomain": "",
        "CertFile": "",
        "CertKey": "",
        "AuthUserIDClaim": "",
        "IdpSignKeyRefreshEnabled": true,
        "ExtraAuthAudience": "{{ .NETBIRD_PROJECT_ID }}"
      },
      "IdpManagerConfig": {
        "ManagerType": "zitadel",
        "ClientConfig": {
          "Issuer": "https://zitadel.example.com",
          "TokenEndpoint": "https://zitadel.example.com/oauth/v2/token",
          "ClientID": "netbird",
          "ClientSecret": "{{ .NETBIRD_SERVICE_USER_CLIENT_SECRET }}",
          "GrantType": "client_credentials"
        },
        "ExtraConfig": {
            "ManagementEndpoint": "https://zitadel.example.com/management/v1"
        }
      },
      "DeviceAuthorizationFlow": {
        "Provider": "hosted",
        "ProviderConfig": {
          "ClientID": "{{ .NETBIRD_CLI_CLIENT_ID }}",
          "ClientSecret": "",
          "Domain": "zitadel.example.com",
          "Audience": "{{ .NETBIRD_CLI_CLIENT_ID }}",
          "TokenEndpoint": "https://zitadel.example.com/oauth/v2/token",
          "DeviceAuthEndpoint": "https://zitadel.example.com/oauth/v2/device_authorization",
          "AuthorizationEndpoint": "",
          "Scope": "openid",
          "UseIDToken": false,
          "RedirectURLs": null
        }
      },
      "PKCEAuthorizationFlow": {
        "ProviderConfig": {
          "ClientID": "{{ .NETBIRD_CLI_CLIENT_ID }}",
          "ClientSecret": "",
          "Domain": "",
          "Audience": "{{ .NETBIRD_CLI_CLIENT_ID }}",
          "DeviceAuthEndpoint": "",
          "Scope": "openid profile email offline_access api groups zitadel:grants",
          "UseIDToken": false,
          "RedirectURLs": ["http://localhost:53000/","http://localhost:54000/"],
          "TokenEndpoint": "https://zitadel.example.com/oauth/v2/token",
          "AuthorizationEndpoint": "https://zitadel.example.com/oauth/v2/authorize"
        }
      },
      "StoreConfig": {
        "Engine": "sqlite"
      },
      "ReverseProxy": {
        "TrustedHTTPProxies": null,
        "TrustedHTTPProxiesCount": 0,
        "TrustedPeers": null
      }
    }
  image:
    tag: 0.30.2
  ingress:
    enabled: false
  ingressGrpc:
    enabled: false
  persistentVolume:
    enabled: true
    size: 5Gi
  envRaw:
    - name: NETBIRD_CLI_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: netbird-preconfig
          key: netbird_cli_client_id
    - name: NETBIRD_SERVICE_USER_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: netbird-preconfig
          key: netbird_service_user_client_secret
    - name: NETBIRD_PROJECT_ID
      valueFrom:
        secretKeyRef:
          name: netbird-preconfig
          key: netbird_project_id
    - name: NETBIRD_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: netbird-preconfig
          key: netbird_client_id
    - name: STUNNER_AUTH_USER
      valueFrom:
        secretKeyRef:
          name: stunner-auth-secret
          key: username
    - name: STUNNER_AUTH_PASS
      valueFrom:
        secretKeyRef:
          name: stunner-auth-secret
          key: password
    - name: DATASTORE_ENCRYPTION_KEY
      valueFrom:
        secretKeyRef:
          name: netbird-datastore-enc-key-secret
          key: key

  podCommand:
    args:
      - --single-account-mode-domain=example.com
      - --log-level=info
      - --log-file=console
      - --disable-anonymous-metrics=true
      - --port=80
      - --dns-domain=netbird.selfhosted"
signal:
  image:
    tag: 0.30.2
  ingress:
    enabled: false
relay:
  enabled: false
  image:
    tag: 0.30.2
  ingress:
    enabled: false
dashboard:
  enabled: true
  ingress:
    enabled: false
  image:
    tag: v2.6.1
  env:
    # Endpoints
    NETBIRD_MGMT_API_ENDPOINT: https://netbird.example.com:443
    NETBIRD_MGMT_GRPC_API_ENDPOINT: https://netbird.example.com:443
    # OIDC
    AUTH_AUTHORITY: https://zitadel.example.com
    USE_AUTH0: false
    AUTH_SUPPORTED_SCOPES: openid profile email offline_access api groups
    AUTH_REDIRECT_URI: /nb-auth
    AUTH_SILENT_REDIRECT_URI: /nb-silent-auth

  envRaw:
    - name: AUTH_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: netbird_preconfig_output_secret
          key: netbird_client_id
    - name: AUTH_AUDIENCE
      valueFrom:
        secretKeyRef:
          name: netbird_preconfig_output_secret
          key: netbird_client_id
