apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbird.fullname" . }}-management
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
data:
  management.tmpl.json: |-
    {{- .Values.management.configmap |nindent 4 }}
