{{- $secretName := printf "%s" (include "netbird.management.secret" .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netbird.fullname" . }}-management
  {{- with .Values.management.deploymentAnnotations }}
  namespace: {{ include "netbird.namespace" . }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "netbird.management.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.management.replicaCount }}
  selector:
    matchLabels:
      {{- include "netbird.management.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/management-cm.yaml") . | sha256sum }}
        {{- with .Values.management.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "netbird.management.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.management.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netbird.management.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.management.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-management
          securityContext:
            {{- toYaml .Values.management.securityContext | nindent 12 }}
          image: "{{ .Values.management.image.repository }}:{{ .Values.management.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.management.image.pullPolicy }}
          {{- if hasKey .Values.management.podCommand "command" }}
          command:
          - {{ .Values.management.podCommand.command }}
          {{- end}}
          {{- if hasKey .Values.management.podCommand "args" }}
          args:
            {{- range .Values.management.podCommand.args }}
          - {{ . }}
          {{- end }}
          {{- end }}
          {{- if or (.Values.management.env) (.Values.management.envRaw) (.Values.management.envFromSecret) }}
          env:
          {{- range $key, $val := .Values.management.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- if .Values.management.envRaw }}
            {{- with .Values.management.envRaw }}
              {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- end }}
          {{- range $key, $val := .Values.management.envFromSecret }}
          - name: {{ .name }}
            valueFrom:
              secretKeyRef:
                name: {{ $secretName }}
                key: {{ .key }}
          {{- end }}
          {{- end }}
          {{- with .Values.management.lifecycle }}
          lifecycle: {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.management.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.management.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/netbird
              name: config
            - mountPath: /var/lib/netbird
              name: management
      {{- with .Values.management.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.management.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.management.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "netbird.fullname" . }}-management
        - name: management
          {{- if .Values.management.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "netbird.fullname" . }}-management
          {{- else }}
          emptyDir: {}
          {{- end }}
