{{- if .Values.relay.enabled -}}

{{- $secretName := printf "%s" (include "netbird.relay.secret" .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netbird.fullname" . }}-relay
  namespace: {{ include "netbird.namespace" . }}
  labels:
    {{- include "netbird.relay.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.relay.replicaCount }}
  selector:
    matchLabels:
      {{- include "netbird.relay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.relay.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "netbird.relay.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.relay.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "netbird.relay.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.relay.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-relay
          securityContext:
            {{- toYaml .Values.relay.securityContext | nindent 12 }}
          image: "{{ .Values.relay.image.repository }}:{{ .Values.relay.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.relay.image.pullPolicy }}
          ports:
            - name: {{ .Values.relay.service.name }}
              containerPort: {{ .Values.relay.service.port }}
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            tcpSocket:
              port: {{ .Values.relay.service.name }}
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            tcpSocket:
              port: {{ .Values.relay.service.name }}
          resources:
            {{- toYaml .Values.relay.resources | nindent 12 }}
          {{- if or (.Values.relay.env) (.Values.relay.envRaw) (.Values.relay.envFromSecret) }}
          env:
            {{- range $key, $val := .Values.relay.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
            {{- if .Values.relay.envRaw }}
              {{- with .Values.relay.envRaw }}
              {{- toYaml . | nindent 10 }}
              {{- end }}
            {{- end }}
            {{- range .Values.relay.envFromSecret }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .key }}
            {{- end }}
          {{- end }}
      {{- with .Values.relay.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.relay.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.relay.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
